### ISSUE TITLE
Windows Defender detecting Trojan:Win32/Casdet!rfn in model-resnet_custom_v3.pt

### ISSUE THREAD

**Issue by MikeMcDonald83** [AUTOMATIC1111/TorchDeepDanbooru#2]
I don't know if this issue is new. I feel like I've used deepdanbooru in automatic1111, but it might have been in my Ubuntu instance. It gets detected whether automatic1111 download or web download.

UPDATE: As of (at least) 3/23/23, Defender no longer detects this library as a threat. As kindly pointed out by Jojo996 below, several other security apps found nothing. Closing this issue.

**Comment by DerHamm3r** [comment]
I am also starting to get this issue since today, I haven't changed anything and just started preprocessing like I usually do and I am getting the same warning from my windows defender. Since it quarantines the file immediately I am also unable to do that right now.

**Comment by tmatzxzone** [comment]
Yea, windows defender just started flagging it as a virus (Trojan:Win32/Casdet!rfn), need to know if it's a false positive or not

**Comment by VandersonQk** [comment]
Same here. I also noticed that if I use it a few times (Interrogate DeepBooru), eventually a system process (sihost.exe) starts using a lot of processor (7%~10%) which makes explorer veeery slow, for example opening a folder takes 2 - 5s. Maybe some instruction in the model is breaking the process and Windows Defender is interpreting this unexpected behavior as a virus.

**Comment by lynnlynn01** [comment]
I am also starting to get this issue since today

**Comment by fong123** [comment]
Any update here?? Im facing this issue too

**Comment by Jojo996Jojo996** [comment]
Virustotal says No security vendors flagged this URL as malicious
https://www.virustotal.com/gui/url/71f0ad7b16a459e63f4b9594758146d3b102f8f2751547662f09f9210ca0b8f1/detection
donno what MS has done.
