### ISSUE TITLE
How to get the file pretrained model-resnet_custom_v3.pt

### ISSUE THREAD

**Issue by pphuc25** [AUTOMATIC1111/TorchDeepDanbooru#3]
I have search for a while and do not find where the file is, can you provide to me a way to have this file

**Comment by bank010** [comment]
> 我已经搜索了一段时间，但没有找到文件的位置，您能否为我提供一种拥有此文件的方法
https://github.com/AUTOMATIC1111/TorchDeepDanbooru/releases/download/v1/model-resnet_custom_v3.pt

**Comment by pphuc25** [comment]
thanks so much, this is so good
